version: '2'

services:
    teamcity:
        image: jetbrains/teamcity-server
        volumes:
            - ./data/server/datadir:/data/teamcity_server/datadir
            - ./data/server/logs:/opt/teamcity/logs
        ports:
            - 8111:8111
    teamcity-agent:
        image: jetbrains/teamcity-agent
        volumes:
            - ./data/agent:/data/teamcity_agent/conf
        environment:
            SERVER_URL: http://dtc:8111
            AGENT_NAME: agent
            TEAMCITY_AGENT_OPTS: -Dproxyset=true -Dhttp.proxyHost=tproxy -Dhttp.proxyPort=8123 -Dhttp.nonProxyHosts=domain.com -Dhttps.proxyHost=tproxy -Dhttps.proxyPort=8123 -Dhttps.nonProxyHosts=domain.com
